databases.admin.folder.ds.datasources.jdbc.ds_mssql.DATABASEURI=jdbc\:jtds\:sqlserver\://localhost\:1433/master;
databases.admin.folder.ds.datasources.jdbc.ds_mssql.USERNAME=sa
databases.admin.folder.ds.datasources.jdbc.ds_mssql.USERPASSWORD=oeCgA4OqQ4jLqKnV9rt4u6zN/1nSWhpQMx5ZHiYziwpc37+94s80m79FPYrJx+WvrDDJYKZ0FlNBBtyMCbV1W5gvGkVPdl7lY1XgFoIYfLfhNaKu13NPi8gPp+e6epOsRZ9sAMO+wH8utM2SuhirFA\=\=
databases.admin.folder.ds.datasources.jdbc.ds_mssql.USERPASSWORD.ENCRYPTED=ENCRYPTED
