databases.admin.folder.ds.datasources.jdbc.ds_mssql.DATABASEURI=jdbc\:jtds\:sqlserver\://localhost\:1433/master;
databases.admin.folder.ds.datasources.jdbc.ds_mssql.USERNAME=sa
databases.admin.folder.ds.datasources.jdbc.ds_mssql.USERPASSWORD=AY0LgDX7Rb7QwL4Q28mO9sCPOJncEyDB4/FTuOE/v6CZbV53joP9eYg4n0rL8OGWVVatYoSywOJGBfsDpJdSTg1kgCZgc73MOiXeN1xdZoOYmiIMhkOyzVRgl2PcJ5SN9b2feT0RgL0eB9Cewh6vBw\=\=
databases.admin.folder.ds.datasources.jdbc.ds_mssql.USERPASSWORD.ENCRYPTED=ENCRYPTED
