databases.admin.folder.ds.datasources.jdbc.oracle_ai26.DATABASEURI=jdbc\:oracle\:thin\:@localhost\:1521/FREE
databases.admin.folder.ds.datasources.jdbc.oracle_ai26.USERNAME=C\#\#DERBY_CONF
databases.admin.folder.ds.datasources.jdbc.oracle_ai26.USERPASSWORD=JfnHC/AV5hgqVOcvMQRHTmetpNQLKZmBNlAxQpknqm2kvjzakA3S/xEzyDDF5hzr0ZZ+kQgFAYarNnrBRYKzqBL3AUtIu5xbPKbLh2kqJc2JSsHtXkqqLcwX9U4R++LmnarRCv62ULui2+O+w/rRLw\=\=
databases.admin.folder.ds.datasources.jdbc.oracle_ai26.USERPASSWORD.ENCRYPTED=ENCRYPTED
