databases.admin.folder.ds.datasources.jdbc.vdpcachedatasource.DATABASEURI=jdbc\:jtds\:sqlserver\://localhost\:1433/master;
databases.admin.folder.ds.datasources.jdbc.vdpcachedatasource.USERNAME=sa
databases.admin.folder.ds.datasources.jdbc.vdpcachedatasource.USERPASSWORD=96fFJiKDDVPZ1vGtTiEMhRy/p4naRMdYSwW2ZwW+Ar+XdCQ5cwTtLvj7cMnCpVLHy4ZPWnwmBNY2sL4s9iFmizpGaf6ZBMInSNr4uWUVhAcR9UrVCrYmd+ukWVNepWzGdndsVF8kYoZgYR/EwA7VXg\=\=
databases.admin.folder.ds.datasources.jdbc.vdpcachedatasource.USERPASSWORD.ENCRYPTED=ENCRYPTED
