# ===========================================================================
# DENODO TESTING TOOL - Configuration
# ===========================================================================
# This is a sample configuration file showing the different parameters that
# can be used for configuring the execution of the Denodo Testing Tool.
# ---------------------------------------------------------------------------
# Three main aspects are configured here:
#  * General configuration parameters (encoding, etc.)
#  * Test reporter implementation
#  * Test data sources
# ===========================================================================



# ---------------------------------------------------------------------------
# GENERAL CONFIGURATION PARAMETERS
# ---------------------------------------------------------------------------

# Encoding that should be used for reading the test files
encoding=UTF-8

# Max number of rows that should be kept in memory during matching operations
# for unordered data. Note that the real amount of memory used depends on
# the real size in bytes of such rows, but this parameter will help limit the
# amount of memory used. The higher this parameter, the less temporary files
# the tool will need for performing unordered data matching.
maxRowsInMemoryForMatching=10000



# ---------------------------------------------------------------------------
# TEST REPORTER
# ---------------------------------------------------------------------------

# Configure the Test Reporter implementation that will be in charge of
# reporting all test events (tool start/end, test start/end, etc.). The
# class declared here must be an implementation of the
# com.denodo.connect.testing.reporter.ITestReporter interface. Also, note that
# users might extend com.denodo.connect.testing.reporter.AbstractTestReporter instead
# in order to override only the event handlers of interest (this abstract
# class implements the whole interface with empty methods).
#
# Multiple Test Reporter implementations might be executed at the same time
# by adding a 'reporter identifier' (e.g. 'csv') as the second element in
# its properties' names.
# ------------------------------
reporter.console=com.denodo.connect.testing.reporter.ConsoleTestReporter
# reporter.csv=com.denodo.connect.testing.reporter.CSVTestReporter
# reporter.csv.pathToOutputFile=src//test//resources//CSVReporter.csv
# reporter.csv.overwriteOutputFileIfExists=true
#
# --------------------
# Example CSV reporter
# --------------------
# reporter.csv=com.denodo.connect.testing.reporter.CSVTestReporter
# reporter.csv.pathToOutputFile=src//test//resources//CSVReporter.csv
# reporter.csv.overwriteOutputFileIfExists=true
#
# ---------------------------
# Example Email Test Reporter
# ---------------------------
# reporter.email=com.denodo.connect.testing.reporter.EmailTestReporter
# reporter.email.username=username@example.net
# reporter.email.password=userpassword
# reporter.email.serverHost=smtp.gmail.com
# reporter.email.serverPort=587
# reporter.email.serverProtocol=smtp
# reporter.email.smtpAuth=true
# reporter.email.smtpStarttlsEnable=true
# reporter.email.smtpQuitwait=false
# # From is a required field that represents who the message is from.
# # It will appear in the from field of the email but depending
# # on the configured SMTP server it must be the same value as the 
# # specified in the username field.
# reporter.email.from=username@example.net
# # Recipients can be separated by spaces or commas
# reporter.email.recipient=username@example.net
# # Available values are: 'full' (all test results reported), 'summary'
# # (only summary with OK/FAILED tests) and 'failed' (email sent only if
# # there have been failed tests).
# reporter.email.messageDetailLevel=full
#
# ---------------------------
# Example HTML Test Reporter
# ---------------------------
# reporter.html=com.denodo.connect.testing.reporter.HTMLTestReporter
# reporter.html.pathToOutputFile=src//test//resources//HTMLReporter.html
# reporter.html.overwriteOutputFileIfExists=true

# ---------------------------------------------------------------------------
# GLOBAL CONTEXT VARIABLES
# ---------------------------------------------------------------------------

# This section allows the specification of context variables that can be
# accessed from any %CONTEXT directive with the #{some.variable} syntax.
#
# Defining global variables here has two advantages: 1. These variables can
# be accessed by ALL tests and 2. variables defined here can be encrypted
# using the Jasypt Command Line Interface tools: http://jasypt.org/cli.html
# and specifying an encryption password by means of the
# DENODO_TEST_ENCRYPTION_PASSWORD environment variable or Java VM system
# property.
#
# some.variable=some value



# ---------------------------------------------------------------------------
# DATA SOURCE CONFIGURATION
# ---------------------------------------------------------------------------
# Each data source referenced from the tests to be executed will need to be
# declared and configured here.
# Available properties are:
#  * [name].driverClassName
#  * [name].jdbcUrl
#  * [name].dbAdapter
#  * [name].username
#  * [name].password
#  * [name].connectionTestQuery

# Example VDP data source
# vdp.driverClassName=com.denodo.vdp.jdbc.Driver
# vdp.jdbcUrl=jdbc:vdb://localhost:9999/test
# vdp.dbAdapter=denodo-9.0.0
# vdp.username=test
# vdp.password=test
# property required for VDP, as JDBC4's Connection.isValid() is not implemented
# vdp.connectionTestQuery=select * from dual()
vdp.driverClassName=com.denodo.vdp.jdbc.Driver
vdp.jdbcUrl=jdbc:vdb://localhost:9999/admin
vdp.dbAdapter=denodo-9.0.0
vdp.username=admin
vdp.password=admin
vdp.connectionTestQuery=select * from dual()


# Example MySQL data source - note the MySQL driver is not included in /lib
# mysql.driverClassName=com.mysql.jdbc.Driver
# mysql.jdbcUrl=jdbc:mysql://localhost/test
# mysql.dbAdapter=mysql-xxx
# mysql.username=test
# mysql.password=test
